title: CSS Project
email: marto054@abv.com
description: HI
destination: docs
baseurl: "/css-newProject"
url: ""
twitter_username: Marto
github_username:  Marto

# Build settings
theme: kramdown
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
